version: 0.2

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
      - pip install --upgrade awscli
  pre_build:
    commands:
      ## Not required 
  build:
    commands:
      - echo Build started on `date`
      - npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
      # Set your AWS region variable
      - export AWS_REGION=ap-southeast-1
      # Configure the CloudGuard Workload Proact security on the SAM template
      - echo Enabling Proact
      - cloudguard proact -m template.yml
      # Set the S3 bucket name variable
      - export S3_BUCKET=chkp-jayden-serverless-apps-source
      # Use AWS SAM to package the application by using AWS CloudFormation
      - echo Enabling FSP
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml


