AWSTemplateFormatVersion: 2010-09-09
Description: cloudguard-serverless-app
Transform:
- AWS::Serverless-2016-10-31
Resources:
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/cloudguardapp.cloudguardHandler
      Runtime: nodejs12.x
      CodeUri: s3://chkp-jayden-serverless-apps-source/b95cc2a70b0899b4a93d310bcd844f0b
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
