version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudguard-serverless-app-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15wdisxie3plf"
s3_prefix = "cloudguard-serverless-app-1"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

